// Code generated by go-swagger; DO NOT EDIT.

package signed_in_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// UnstarDashboardByUIDReader is a Reader for the UnstarDashboardByUID structure.
type UnstarDashboardByUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnstarDashboardByUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnstarDashboardByUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUnstarDashboardByUIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUnstarDashboardByUIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUnstarDashboardByUIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUnstarDashboardByUIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUnstarDashboardByUIDOK creates a UnstarDashboardByUIDOK with default headers values
func NewUnstarDashboardByUIDOK() *UnstarDashboardByUIDOK {
	return &UnstarDashboardByUIDOK{}
}

/*
UnstarDashboardByUIDOK describes a response with status code 200, with default header values.

An OKResponse is returned if the request was successful.
*/
type UnstarDashboardByUIDOK struct {
	Payload *models.SuccessResponseBody
}

func (o *UnstarDashboardByUIDOK) Error() string {
	return fmt.Sprintf("[DELETE /user/stars/dashboard/uid/{dashboard_uid}][%d] unstarDashboardByUidOK  %+v", 200, o.Payload)
}
func (o *UnstarDashboardByUIDOK) GetPayload() *models.SuccessResponseBody {
	return o.Payload
}

func (o *UnstarDashboardByUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnstarDashboardByUIDBadRequest creates a UnstarDashboardByUIDBadRequest with default headers values
func NewUnstarDashboardByUIDBadRequest() *UnstarDashboardByUIDBadRequest {
	return &UnstarDashboardByUIDBadRequest{}
}

/*
UnstarDashboardByUIDBadRequest describes a response with status code 400, with default header values.

BadRequestError is returned when the request is invalid and it cannot be processed.
*/
type UnstarDashboardByUIDBadRequest struct {
	Payload *models.ErrorResponseBody
}

func (o *UnstarDashboardByUIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /user/stars/dashboard/uid/{dashboard_uid}][%d] unstarDashboardByUidBadRequest  %+v", 400, o.Payload)
}
func (o *UnstarDashboardByUIDBadRequest) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UnstarDashboardByUIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnstarDashboardByUIDUnauthorized creates a UnstarDashboardByUIDUnauthorized with default headers values
func NewUnstarDashboardByUIDUnauthorized() *UnstarDashboardByUIDUnauthorized {
	return &UnstarDashboardByUIDUnauthorized{}
}

/*
UnstarDashboardByUIDUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type UnstarDashboardByUIDUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *UnstarDashboardByUIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /user/stars/dashboard/uid/{dashboard_uid}][%d] unstarDashboardByUidUnauthorized  %+v", 401, o.Payload)
}
func (o *UnstarDashboardByUIDUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UnstarDashboardByUIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnstarDashboardByUIDForbidden creates a UnstarDashboardByUIDForbidden with default headers values
func NewUnstarDashboardByUIDForbidden() *UnstarDashboardByUIDForbidden {
	return &UnstarDashboardByUIDForbidden{}
}

/*
UnstarDashboardByUIDForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type UnstarDashboardByUIDForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *UnstarDashboardByUIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /user/stars/dashboard/uid/{dashboard_uid}][%d] unstarDashboardByUidForbidden  %+v", 403, o.Payload)
}
func (o *UnstarDashboardByUIDForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UnstarDashboardByUIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnstarDashboardByUIDInternalServerError creates a UnstarDashboardByUIDInternalServerError with default headers values
func NewUnstarDashboardByUIDInternalServerError() *UnstarDashboardByUIDInternalServerError {
	return &UnstarDashboardByUIDInternalServerError{}
}

/*
UnstarDashboardByUIDInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type UnstarDashboardByUIDInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *UnstarDashboardByUIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /user/stars/dashboard/uid/{dashboard_uid}][%d] unstarDashboardByUidInternalServerError  %+v", 500, o.Payload)
}
func (o *UnstarDashboardByUIDInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *UnstarDashboardByUIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
