// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Duration Duration is a type used for marshalling durations.
//
// swagger:model Duration
type Duration int64

// Validate validates this duration
func (m Duration) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this duration based on context it is used
func (m Duration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
