// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Playlist Playlist model
//
// swagger:model Playlist
type Playlist struct {

	// id
	ID int64 `json:"id,omitempty"`

	// Interval sets the time between switching views in a playlist.
	// FIXME: Is this based on a standardized format or what options are available? Can datemath be used?
	Interval string `json:"interval,omitempty"`

	// Name of the playlist.
	Name string `json:"name,omitempty"`

	// Unique playlist identifier. Generated on creation, either by the
	// creator of the playlist of by the application.
	UID string `json:"uid,omitempty"`
}

// Validate validates this playlist
func (m *Playlist) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this playlist based on context it is used
func (m *Playlist) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Playlist) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Playlist) UnmarshalBinary(b []byte) error {
	var res Playlist
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
