// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PlaylistItemType Type of the item.
//
// THIS TYPE IS INTENDED FOR INTERNAL USE BY THE GRAFANA BACKEND, AND IS SUBJECT TO BREAKING CHANGES.
// Equivalent Go types at stable import paths are provided in https://github.com/grafana/grok.
//
// swagger:model PlaylistItemType
type PlaylistItemType string

// Validate validates this playlist item type
func (m PlaylistItemType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this playlist item type based on context it is used
func (m PlaylistItemType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
