// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/esnet/grafana-swagger-api-golang/goclient/models"
)

// RouteGetAlertRuleGroupExportReader is a Reader for the RouteGetAlertRuleGroupExport structure.
type RouteGetAlertRuleGroupExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetAlertRuleGroupExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetAlertRuleGroupExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetAlertRuleGroupExportNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRouteGetAlertRuleGroupExportOK creates a RouteGetAlertRuleGroupExportOK with default headers values
func NewRouteGetAlertRuleGroupExportOK() *RouteGetAlertRuleGroupExportOK {
	return &RouteGetAlertRuleGroupExportOK{}
}

/*
RouteGetAlertRuleGroupExportOK describes a response with status code 200, with default header values.

AlertingFileExport
*/
type RouteGetAlertRuleGroupExportOK struct {
	Payload *models.AlertingFileExport
}

func (o *RouteGetAlertRuleGroupExportOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}/export][%d] routeGetAlertRuleGroupExportOK  %+v", 200, o.Payload)
}
func (o *RouteGetAlertRuleGroupExportOK) GetPayload() *models.AlertingFileExport {
	return o.Payload
}

func (o *RouteGetAlertRuleGroupExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertingFileExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetAlertRuleGroupExportNotFound creates a RouteGetAlertRuleGroupExportNotFound with default headers values
func NewRouteGetAlertRuleGroupExportNotFound() *RouteGetAlertRuleGroupExportNotFound {
	return &RouteGetAlertRuleGroupExportNotFound{}
}

/*
RouteGetAlertRuleGroupExportNotFound describes a response with status code 404, with default header values.

	Not found.
*/
type RouteGetAlertRuleGroupExportNotFound struct {
}

func (o *RouteGetAlertRuleGroupExportNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}/export][%d] routeGetAlertRuleGroupExportNotFound ", 404)
}

func (o *RouteGetAlertRuleGroupExportNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
