// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/esnet/grafana-swagger-api-golang/goclient/models"
)

// RouteGetAlertRulesExportReader is a Reader for the RouteGetAlertRulesExport structure.
type RouteGetAlertRulesExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetAlertRulesExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetAlertRulesExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetAlertRulesExportNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRouteGetAlertRulesExportOK creates a RouteGetAlertRulesExportOK with default headers values
func NewRouteGetAlertRulesExportOK() *RouteGetAlertRulesExportOK {
	return &RouteGetAlertRulesExportOK{}
}

/*
RouteGetAlertRulesExportOK describes a response with status code 200, with default header values.

AlertingFileExport
*/
type RouteGetAlertRulesExportOK struct {
	Payload *models.AlertingFileExport
}

func (o *RouteGetAlertRulesExportOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/export][%d] routeGetAlertRulesExportOK  %+v", 200, o.Payload)
}
func (o *RouteGetAlertRulesExportOK) GetPayload() *models.AlertingFileExport {
	return o.Payload
}

func (o *RouteGetAlertRulesExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertingFileExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetAlertRulesExportNotFound creates a RouteGetAlertRulesExportNotFound with default headers values
func NewRouteGetAlertRulesExportNotFound() *RouteGetAlertRulesExportNotFound {
	return &RouteGetAlertRulesExportNotFound{}
}

/*
RouteGetAlertRulesExportNotFound describes a response with status code 404, with default header values.

	Not found.
*/
type RouteGetAlertRulesExportNotFound struct {
}

func (o *RouteGetAlertRulesExportNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/export][%d] routeGetAlertRulesExportNotFound ", 404)
}

func (o *RouteGetAlertRulesExportNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
