// Code generated by go-swagger; DO NOT EDIT.

package correlations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// GetCorrelationsReader is a Reader for the GetCorrelations structure.
type GetCorrelationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCorrelationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCorrelationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCorrelationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCorrelationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCorrelationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCorrelationsOK creates a GetCorrelationsOK with default headers values
func NewGetCorrelationsOK() *GetCorrelationsOK {
	return &GetCorrelationsOK{}
}

/*
GetCorrelationsOK describes a response with status code 200, with default header values.

(empty)
*/
type GetCorrelationsOK struct {
	Payload []*models.Correlation
}

func (o *GetCorrelationsOK) Error() string {
	return fmt.Sprintf("[GET /datasources/correlations][%d] getCorrelationsOK  %+v", 200, o.Payload)
}
func (o *GetCorrelationsOK) GetPayload() []*models.Correlation {
	return o.Payload
}

func (o *GetCorrelationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorrelationsUnauthorized creates a GetCorrelationsUnauthorized with default headers values
func NewGetCorrelationsUnauthorized() *GetCorrelationsUnauthorized {
	return &GetCorrelationsUnauthorized{}
}

/*
GetCorrelationsUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type GetCorrelationsUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *GetCorrelationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /datasources/correlations][%d] getCorrelationsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetCorrelationsUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCorrelationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorrelationsNotFound creates a GetCorrelationsNotFound with default headers values
func NewGetCorrelationsNotFound() *GetCorrelationsNotFound {
	return &GetCorrelationsNotFound{}
}

/*
GetCorrelationsNotFound describes a response with status code 404, with default header values.

NotFoundError is returned when the requested resource was not found.
*/
type GetCorrelationsNotFound struct {
	Payload *models.ErrorResponseBody
}

func (o *GetCorrelationsNotFound) Error() string {
	return fmt.Sprintf("[GET /datasources/correlations][%d] getCorrelationsNotFound  %+v", 404, o.Payload)
}
func (o *GetCorrelationsNotFound) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCorrelationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorrelationsInternalServerError creates a GetCorrelationsInternalServerError with default headers values
func NewGetCorrelationsInternalServerError() *GetCorrelationsInternalServerError {
	return &GetCorrelationsInternalServerError{}
}

/*
GetCorrelationsInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type GetCorrelationsInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *GetCorrelationsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /datasources/correlations][%d] getCorrelationsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetCorrelationsInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCorrelationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
