// Code generated by go-swagger; DO NOT EDIT.

package correlations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// GetCorrelationReader is a Reader for the GetCorrelation structure.
type GetCorrelationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCorrelationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCorrelationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCorrelationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCorrelationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCorrelationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCorrelationOK creates a GetCorrelationOK with default headers values
func NewGetCorrelationOK() *GetCorrelationOK {
	return &GetCorrelationOK{}
}

/*
GetCorrelationOK describes a response with status code 200, with default header values.

(empty)
*/
type GetCorrelationOK struct {
	Payload *models.Correlation
}

func (o *GetCorrelationOK) Error() string {
	return fmt.Sprintf("[GET /datasources/uid/{sourceUID}/correlations/{correlationUID}][%d] getCorrelationOK  %+v", 200, o.Payload)
}
func (o *GetCorrelationOK) GetPayload() *models.Correlation {
	return o.Payload
}

func (o *GetCorrelationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Correlation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorrelationUnauthorized creates a GetCorrelationUnauthorized with default headers values
func NewGetCorrelationUnauthorized() *GetCorrelationUnauthorized {
	return &GetCorrelationUnauthorized{}
}

/*
GetCorrelationUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type GetCorrelationUnauthorized struct {
	Payload *models.ErrorResponseBody
}

func (o *GetCorrelationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /datasources/uid/{sourceUID}/correlations/{correlationUID}][%d] getCorrelationUnauthorized  %+v", 401, o.Payload)
}
func (o *GetCorrelationUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCorrelationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorrelationNotFound creates a GetCorrelationNotFound with default headers values
func NewGetCorrelationNotFound() *GetCorrelationNotFound {
	return &GetCorrelationNotFound{}
}

/*
GetCorrelationNotFound describes a response with status code 404, with default header values.

NotFoundError is returned when the requested resource was not found.
*/
type GetCorrelationNotFound struct {
	Payload *models.ErrorResponseBody
}

func (o *GetCorrelationNotFound) Error() string {
	return fmt.Sprintf("[GET /datasources/uid/{sourceUID}/correlations/{correlationUID}][%d] getCorrelationNotFound  %+v", 404, o.Payload)
}
func (o *GetCorrelationNotFound) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCorrelationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorrelationInternalServerError creates a GetCorrelationInternalServerError with default headers values
func NewGetCorrelationInternalServerError() *GetCorrelationInternalServerError {
	return &GetCorrelationInternalServerError{}
}

/*
GetCorrelationInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type GetCorrelationInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *GetCorrelationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /datasources/uid/{sourceUID}/correlations/{correlationUID}][%d] getCorrelationInternalServerError  %+v", 500, o.Payload)
}
func (o *GetCorrelationInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCorrelationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
