// Code generated by go-swagger; DO NOT EDIT.

package access_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-api-golang-client/goclient/models"
)

// GetRoleAssignmentsReader is a Reader for the GetRoleAssignments structure.
type GetRoleAssignmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoleAssignmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoleAssignmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetRoleAssignmentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRoleAssignmentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRoleAssignmentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRoleAssignmentsOK creates a GetRoleAssignmentsOK with default headers values
func NewGetRoleAssignmentsOK() *GetRoleAssignmentsOK {
	return &GetRoleAssignmentsOK{}
}

/*
GetRoleAssignmentsOK describes a response with status code 200, with default header values.

(empty)
*/
type GetRoleAssignmentsOK struct {
	Payload *models.RoleAssignmentsDTO
}

func (o *GetRoleAssignmentsOK) Error() string {
	return fmt.Sprintf("[GET /access-control/roles/{roleUID}/assignments][%d] getRoleAssignmentsOK  %+v", 200, o.Payload)
}
func (o *GetRoleAssignmentsOK) GetPayload() *models.RoleAssignmentsDTO {
	return o.Payload
}

func (o *GetRoleAssignmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoleAssignmentsDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleAssignmentsForbidden creates a GetRoleAssignmentsForbidden with default headers values
func NewGetRoleAssignmentsForbidden() *GetRoleAssignmentsForbidden {
	return &GetRoleAssignmentsForbidden{}
}

/*
GetRoleAssignmentsForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type GetRoleAssignmentsForbidden struct {
	Payload *models.ErrorResponseBody
}

func (o *GetRoleAssignmentsForbidden) Error() string {
	return fmt.Sprintf("[GET /access-control/roles/{roleUID}/assignments][%d] getRoleAssignmentsForbidden  %+v", 403, o.Payload)
}
func (o *GetRoleAssignmentsForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetRoleAssignmentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleAssignmentsNotFound creates a GetRoleAssignmentsNotFound with default headers values
func NewGetRoleAssignmentsNotFound() *GetRoleAssignmentsNotFound {
	return &GetRoleAssignmentsNotFound{}
}

/*
GetRoleAssignmentsNotFound describes a response with status code 404, with default header values.

NotFoundError is returned when the requested resource was not found.
*/
type GetRoleAssignmentsNotFound struct {
	Payload *models.ErrorResponseBody
}

func (o *GetRoleAssignmentsNotFound) Error() string {
	return fmt.Sprintf("[GET /access-control/roles/{roleUID}/assignments][%d] getRoleAssignmentsNotFound  %+v", 404, o.Payload)
}
func (o *GetRoleAssignmentsNotFound) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetRoleAssignmentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoleAssignmentsInternalServerError creates a GetRoleAssignmentsInternalServerError with default headers values
func NewGetRoleAssignmentsInternalServerError() *GetRoleAssignmentsInternalServerError {
	return &GetRoleAssignmentsInternalServerError{}
}

/*
GetRoleAssignmentsInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type GetRoleAssignmentsInternalServerError struct {
	Payload *models.ErrorResponseBody
}

func (o *GetRoleAssignmentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /access-control/roles/{roleUID}/assignments][%d] getRoleAssignmentsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetRoleAssignmentsInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetRoleAssignmentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
